<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Žinutės</title>
    <link rel="stylesheet" media="screen" type="text/css" href="css/screen.css" />
    <script
            src="http://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
</head>
<body>
<div id="wrapper">
    <h1>Jūsų žinutės</h1>
    <form method="post" action="/">
        <p class="<?=$formErrors['first_name']?>">
            <label for="first_name">Vardas *</label><br/>
            <input id="first_name" type="text" name="first_name" value="<?=$fromValues['first_name']?>" required/>
        </p>
        <p class="<?=$formErrors['last_name']?>">
            <label for="last_name">Pavardė *</label><br/>
            <input id="last_name" type="text" name="last_name" value="<?=$fromValues['last_name']?>" required/>
        </p>
        <p class="<?=$formErrors['birthdate']?>">
            <label for="birthdate">Gimimo data *</label><br/>
            <input id="birthdate" type="text" placeholder="YYYY-MM-DD" name="birthdate" value="<?=$fromValues['birthdate']?>" required/>
        </p>
        <p class="<?=$formErrors['email']?>">
            <label for="email">El.pašto adresas</label><br/>
            <input id="email" type="text" name="email" value="<?=$fromValues['email']?>" />
        </p>
        <p class="<?=$formErrors['message']?>">
            <label for="message">Jūsų žinutė *</label><br/>
            <textarea id="message" name="message" required><?=$fromValues['message']?></textarea>
        </p>
        <p>
            <span>* - privalomi laukai</span>
            <input id="message_submit" type="submit" value="Skelbti" />
            <img id="loader-gif" class="hidden" src="img/ajax-loader.gif" alt="loader" />
        </p>
    </form>
    <ul>
        <li>
            <strong>Šiuo metu žinučių nėra. Būk pirmas!</strong>
        </li>
        <li>
            <span>2010 01 01 08:59</span> <a href="mailto:example@example.com">Vardas Pavardė</a>, 13 m.<br/>
            Įkėlėme šeimos dienos akciją. Dėl papildomos medžiagos užtrukome šiek tiek ilgiau nei įprasta.
        </li>
        <li>
            <span>2010 01 01 08:59</span> Vardas Pavardė, 75 m. <br/>
            Įkėlėme šeimos dienos akciją. Dėl papildomos medžiagos užtrukome šiek tiek ilgiau nei įprasta.
        </li>
        <li>
            <span>2010 01 01 08:59</span> Vardas Pavardė, 10 m. <br/>
            Įkėlėme šeimos dienos akciją. Dėl papildomos medžiagos užtrukome šiek tiek ilgiau nei įprasta.
        </li>
        <li>
            <span>2010 01 01 08:59</span> <a href="mailto:example@example.com">Vardas Pavardė</a>, 25 m. <br/>
            Įkėlėme šeimos dienos akciją. Dėl papildomos medžiagos užtrukome šiek tiek ilgiau nei įprasta.
        </li>
        <li>
            <span>2010 01 01 08:59</span> Vardas Pavardė, 26 m. <br/>
            Įkėlėme šeimos dienos akciją. Dėl papildomos medžiagos užtrukome šiek tiek ilgiau nei įprasta.
        </li>
    </ul>
    <p id="pages">
        <a href="#" title="atgal">atgal</a>
        <a href="#" title="1">1</a>
        2
        <a href="#" title="3">3</a>
        <a href="#" title="4">4</a>
        <a href="#" title="toliau">toliau</a>
    </p>
</div>
</body>
<script src="js/message_board.js"></script>
</html>