<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Žinutės</title>
    <link rel="stylesheet" media="screen" type="text/css" href="css/screen.css" />
    <script
            src="http://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
</head>
<body>
<div id="wrapper">
    <h1>Jūsų žinutės</h1>
    <form method="post" action="/">
        <p class="<?=$formErrors['first_name']?>">
            <label for="first_name">Vardas *</label><br/>
            <input id="first_name" type="text" name="first_name" maxlength="<?=$formFieldRules['name_max_length']?>" value="<?=$fromValues['first_name']?>" required/>
        </p>
        <p class="<?=$formErrors['last_name']?>">
            <label for="last_name">Pavardė *</label><br/>
            <input id="last_name" type="text" name="last_name" maxlength="<?=$formFieldRules['name_max_length']?>" value="<?=$fromValues['last_name']?>" required/>
        </p>
        <p class="<?=$formErrors['birthdate']?>">
            <label for="birthdate">Gimimo data *</label><br/>
            <input id="birthdate" type="text" placeholder="<?=$formFieldRules['birthdate_format_example']?>" name="birthdate" value="<?=$fromValues['birthdate']?>" required/>
        </p>
        <p class="<?=$formErrors['email']?>">
            <label for="email">El.pašto adresas</label><br/>
            <input id="email" type="text" name="email" value="<?=$fromValues['email']?>" />
        </p>
        <p class="<?=$formErrors['message']?>">
            <label for="message">Jūsų žinutė *</label><br/>
            <textarea id="message" name="message" maxlength="<?=$formFieldRules['message_max_length']?>" required><?=$fromValues['message']?></textarea>
        </p>
        <p>
            <span>* - privalomi laukai</span>
            <input id="message_submit" type="submit" value="Skelbti" />
            <img id="loader-gif" class="hidden" src="img/ajax-loader.gif" alt="loader" />
        </p>
    </form>
    <ul id="message-container">

        <?php if($messagesPagination->total() == 0):?>
            <li>
                <strong>Šiuo metu žinučių nėra. Būk pirmas!</strong>
            </li>
        <?php else:?>
            <?php foreach ($messagesForPage as $message):?>
                <li>
                    <div>
                        <span><?=$message->getTime()->format('Y m d H:i')?></span>
                        <?php if ($message->getUser()->getEmail() != ''):?>
                        <a href="mailto:<?=$message->getUser()->getEmail()?>"><?=$message->getUser()->getFirstName()?> <?=$message->getUser()->getLastName()?></a>
                        <?php else:?>
                        <?=$message->getUser()->getFirstName()?> <?=$message->getUser()->getLastName()?>
                        <?php endif;?>
                        , <?=$message->getUser()->getAge()?> m.
                    </div>
                    <div>
                        <?=$message->getMessage()?>
                    </div>
                </li>
            <?php endforeach;?>
        <?php endif;?>
    </ul>
    <p id="pages">
        <?php if ($messagesPagination->total() > 0):?>
            <?php if($messagesPagination->currentPage() > 1):?>
                <a href="/?page=<?=$messagesPagination->currentPage() - 1?>" title="atgal">atgal</a>
            <?php endif;?>

            <?php for($i = 1; $i <= $messagesPagination->lastPage(); $i++):?>
                <?php if($i == $messagesPagination->currentPage()):?>
                    <?=$i?>
                <?php else:?>
                    <a href="/?page=<?=$i?>" title="<?=$i?>"><?=$i?></a>
                <?php endif;?>
            <?php endfor;?>

            <?php if($messagesPagination->currentPage() < $messagesPagination->lastPage()):?>
                <a href="/?page=<?=$messagesPagination->currentPage() + 1?>" title="toliau">toliau</a>
            <?php endif;?>
        <?php endif;?>
    </p>

</div>
</body>
<script src="js/message_board.js"></script>
</html>